### ISSUE TITLE
Attempting to access /phpmyadmin server returns 502 Bad Gateway

### ISSUE THREAD

**Issue by stuartshields** [Chassis/phpMyAdmin#13]
error.log shows the following:

```2017/03/21 23:40:23 [error] 2690#0: *763 upstream sent too big header while reading response header from upstream, client: 10.86.73.1, server: thechive-preview.x-team.vvv, request: "GET /phpmyadmin/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "thechive-preview.x-team.vvv"```

**Comment by stuartshields** [comment]
FWIW, I'm running PHP7, so I'm not sure if the PHP5-fpm could be an issue.

**Comment by ntwb** [comment]
It works for me using PHP 7.0 with Chassis 1.x and 2.x (Xenial) without issue

See Slack discussion https://wpaustralia.slack.com/archives/C0332QP9J/p1490149117084563

**Comment by BronsonQuick** [comment]
I'm closing this as I couldn't replicate it
