### ISSUE TITLE
Update to 4.7.7

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/phpMyAdmin#17]

**Comment by ntwb** [comment]
Via https://www.phpmyadmin.net/security/PMASA-2017-9/
> XSRF/CSRF vulnerability in phpMyAdmin
> Affected Versions: Versions 4.7.x (prior to 4.7.7) are affected.
> Unaffected Versions: Versions older than 4.7.0 are not affected.
> Solution: Upgrade to phpMyAdmin 4.7.7 or newer or apply patch listed below.
