### ISSUE TITLE
Can't provision on Windows 10

### ISSUE THREAD

**Issue by cameronjonesweb** [Chassis/phpMyAdmin#3]
Maybe I'm doing something wrong but this is what I get when I try to provision after cloning into the extensions folder. It hasn't been updated for a while so perhaps something's changed.
```
==> default: Error: Could not set 'link' on ensure: Protocol error - /vagrant/extensions/phpmyadmin/phpmyadmin or /vagrant/phpmyadmin at 16:/vagrant/extensions/phpMyAdmin/modules/phpmyadmin/manifests/init.pp
==> default: Error: Could not set 'link' on ensure: Protocol error - /vagrant/extensions/phpmyadmin/phpmyadmin or /vagrant/phpmyadmin at 16:/vagrant/extensions/phpMyAdmin/modules/phpmyadmin/manifests/init.pp
==> default: Wrapped exception:
==> default: Protocol error - /vagrant/extensions/phpmyadmin/phpmyadmin or /vagrant/phpmyadmin
==> default: Error: /Stage[main]/Phpmyadmin/File[/vagrant/phpmyadmin]/ensure: change from absent to link failed: Could not set 'link' on ensure: Protocol error - /vagrant/extensions/phpmyadmin/phpmyadmin or /vagrant/phpmyadmin at 16:/vagrant/extensions/phpMyAdmin/modules/phpmyadmin/manifests/init.pp
==> default: Notice: /Stage[main]/Phpmyadmin/File[/vagrant/extensions/phpmyadmin/phpmyadmin/config.inc.php]/mode: mode changed '0777' to '0600'
==> default: Notice: /Stage[main]/Chassis/Service[nginx]: Dependency File[/vagrant/phpmyadmin] has failures: true
==> default: Warning: /Stage[main]/Chassis/Service[nginx]: Skipping because of failed dependencies
==> default: Notice: Finished catalog run in 1.51 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by BronsonQuick** [comment]
Hey @cameronjonesweb sorry for the delay. We've just had the Human Made retreat and I'm only just adjusting to jet lag and catching up on issues. I'll have a look into this now for you!

**Comment by cameronjonesweb** [comment]
No worries @BronsonQuick all good I figured you guys would be still making your way back from WCEU

**Comment by BronsonQuick** [comment]
Hey @cameronjonesweb looks like I can't replicate this:

<img width="1661" alt="phpmyadmin" src="https://cloud.githubusercontent.com/assets/1377956/16607810/c0ef1f4a-4388-11e6-90f3-51d95d870960.png">

Any chance you might be able to give me a little more information?

**Comment by cameronjonesweb** [comment]
Unfortunately I'm still getting the same errors today (I had my fingers crossed updating the phpMyAdmin version would have fixed it). It's running an almost entirely clean instance of Chassis, only default changed is the host, so the PHP version is 5.6. Running on Windows 10, that's probably the only thing I can think of that would be different about our setups. Perhaps related to Chassis/Chassis/issues/136 with issues on Windows.

Let me know if there's any files or logs you want me to send you to look at

**Comment by BronsonQuick** [comment]
>only default changed is the host

That might be the issue. Can you please do me a massive favour and clone a default Chassis into a new folder, clone this extension and then do a `vagrant up`. If that works then it's definitely the host and I'll dig through the code to fix it.

If that doesn't work then I'll boot up my Windows box and get cracking at that. Thanks!

**Comment by cameronjonesweb** [comment]
Still running into the same error with a default Chassis instance. Tried both `vagrant up` before installing the extension and attempting to `vagrant provision`, and installing the extension before attempting `vagrant up`
![image](https://cloud.githubusercontent.com/assets/12673074/16617005/6fb8034e-43c4-11e6-938a-b0257f213245.png)

**Comment by BronsonQuick** [comment]
@cameronjonesweb Awesome. Thanks again! So I've dug through the docs and this is definitely a Windows issue:

I'm using the `file` resource type in Puppet for this and the docs have this written:
```
link ensures the file is a symlink, and requires that you also set the target attribute. Symlinks are supported on all Posix systems and on Windows Vista / 2008 and higher. On Windows, managing symlinks requires Puppet agent’s user account to have the “Create Symbolic Links” privilege; this can be configured in the “User Rights Assignment” section in the Windows policy editor. By default, Puppet agent runs as the Administrator account, which has this privilege.
```

Can you please try fixing that manually and trying again? If that works then I'll need to do a PR to update the docs. If you get it to work could you also attach some steps and screenshots for me so I can add them to the docs please? Thanks heaps!

**Comment by BronsonQuick** [comment]
>By default, Puppet agent runs as the Administrator account, which has this privilege.

I'm not sure if that's the case. I'm guessing it's not!

**Comment by cameronjonesweb** [comment]
I would have thought it would be, but apparently not! Resolves simply with a right click on the command  prompt shortcut and selecting run as administrator.
![run as admin](https://cloud.githubusercontent.com/assets/12673074/16652866/b015ca76-4490-11e6-972b-f29c9b9a2da3.png)

However, I will see if I can figure out a process to get this to work without running the command prompt as an administrator by giving the user the appropriate permissions.

**Comment by BronsonQuick** [comment]
@cameronjonesweb Awesome. Thanks for letting me know that at least works. Let me know if you have any luck with a workaround. If not then I'll just update the docs! 😄

**Comment by renatonascalves** [comment]
@cameronjonesweb Thanks! I was with the same problem on Windows 10. Your answer resolved the same issue... =D

**Comment by cameronjonesweb** [comment]
@BronsonQuick This guide works for making a program run as an administrator by default: http://www.cnet.com/au/how-to/always-run-a-program-in-administrator-mode-in-windows-10/

**Comment by dcneuts** [comment]
@BronsonQuick I'm just coming online with Vagrant and Chassis, and while it's been working great so far, I'm not able to get the phpMyAdmin extension to function properly, the same as noted above.  I also attempted with a new install and configure and followed the "run program as administrator" guide for Windows 10, but to no avail.

![Screenshot 07-29-2019 18 42 20](https://user-images.githubusercontent.com/21981450/62094062-9c2ed500-b230-11e9-8202-12e9f0bf0de4.png)

**Comment by ntwb** [comment]
When running as an administrator @dcneuts you should see `Administrator` in the title bar of the window:

<img width="403" alt="Screen Shot 2019-07-30 at 12 57 05 pm" src="https://user-images.githubusercontent.com/1016458/62097255-93d6a880-b2c9-11e9-8d1e-691179c13858.png">

**Comment by dcneuts** [comment]
@ntwb Thanks for lending an assist!  You'll be pleased to know that after a reboot, this worked without incident.

The prior test also used this same method, as well as Git Bash versus the native command prompt, and failed.  I'm very happy that this is now simply working.

![Screenshot 07-30-2019 03 23 01](https://user-images.githubusercontent.com/21981450/62098383-ea4ad500-b23e-11e9-94e8-40bcb4a331ee.png)
