### ISSUE TITLE
File mode changes on every provision

### ISSUE THREAD

**Issue by noplanman** [Chassis/phpMyAdmin#8]
On every provision I get this message:
`==> default: Notice: /Stage[main]/Phpmyadmin/File[/vagrant/extensions/phpmyadmin/phpmyadmin/config.inc.php]/mode: mode changed '0777' to '0755'`

Is this normal? Shouldn't it be set and then stay like that?

**Comment by BronsonQuick** [comment]
Hey @noplanman,

That's definitely not normal. It should be set and stay like that. I haven't been able to replicate this locally:
![phpmyadmin](https://cloud.githubusercontent.com/assets/1377956/21582666/093eb2b4-d0b6-11e6-890f-9942fac8285e.png)

To try and help me replicate it could you please let me know what operating system you're running and the versions of Vagrant and VirtualBox or VMware that you're using? Thanks!

**Comment by noplanman** [comment]
Hi @BronsonQuick, sure thing!

```
OS:      OSX Mavericks (10.9.5)
VBox:    5.0.26
Vagrant: 1.9.1
```

This is my output by the way:
```
$ vagrant provision 
==> default: Running provisioner: shell...
    default: Running: /var/folders/y9/d6pb7b1132sc25xpmdlrym500000gn/T/vagrant-shell20161229-63088-o1tyjx.sh
==> default: stdin: is not a tty
==> default: Running provisioner: puppet...
==> default: Running Puppet with development.pp...
==> default: stdin: is not a tty
==> default: Notice: Compiled catalog for plugin-dev.local in environment production in 4.04 seconds
==> default: Notice: /Stage[main]/Phpmyadmin/File[/vagrant/extensions/phpmyadmin/phpmyadmin/config.inc.php]/mode: mode changed '0777' to '0755'
==> default: Notice: /Stage[main]/Debugging/Wp::Plugin[debug-bar-transients]/Wp::Command[/vagrant/wp plugin debug-bar-transients enabled]/Exec[/vagrant/wp wp plugin activate debug-bar-transients]/returns: executed successfully
==> default: Notice: /Stage[main]/Debugging/Wp::Plugin[debug-bar-extender]/Wp::Command[/vagrant/wp plugin debug-bar-extender enabled]/Exec[/vagrant/wp wp plugin activate debug-bar-extender]/returns: executed successfully
==> default: Notice: /Stage[main]/Debugging/Wp::Plugin[log-deprecated-notices]/Wp::Command[/vagrant/wp plugin log-deprecated-notices enabled]/Exec[/vagrant/wp wp plugin activate log-deprecated-notices]/returns: executed successfully
==> default: Notice: /Stage[main]/Debugging/Wp::Plugin[debug-bar-cron]/Wp::Command[/vagrant/wp plugin debug-bar-cron enabled]/Exec[/vagrant/wp wp plugin activate debug-bar-cron]/returns: executed successfully
==> default: Notice: /Stage[main]/Debugging/Wp::Plugin[debug-bar]/Wp::Command[/vagrant/wp plugin debug-bar enabled]/Exec[/vagrant/wp wp plugin activate debug-bar]/returns: executed successfully
==> default: Notice: /Stage[main]/Debugging/Wp::Plugin[rewrite-rules-inspector]/Wp::Command[/vagrant/wp plugin rewrite-rules-inspector enabled]/Exec[/vagrant/wp wp plugin activate rewrite-rules-inspector]/returns: executed successfully
==> default: Notice: Finished catalog run in 25.33 seconds
==> default: Running provisioner: shell...
    default: Running: /var/folders/y9/d6pb7b1132sc25xpmdlrym500000gn/T/vagrant-shell20161229-63088-1a4jvo7.sh
==> default: stdin: is not a tty
```

As you can see, the `Chassis/Debugging` plugins create the same output every time too, is *that* normal?

**Comment by BronsonQuick** [comment]
@noplanman Ahh awesome. Thanks for the additional info. I'm just about to try and replicate this now and dig into it.

One more question for you, can you please give me a list of all the Chassis extensions you're using? Is it just Debugging and phpmyadmin? Thanks heaps!

**Comment by noplanman** [comment]
In my `config.local.yaml`
```
extensions:
  - git@github.com:Chassis/composer.git
  - git@github.com:Chassis/db-backup.git
  - git@github.com:Chassis/mailhog.git
  - git@github.com:Chassis/phpmyadmin.git
  - git@github.com:Chassis/Debugging.git
```

**Comment by BronsonQuick** [comment]
@noplanman Champion. Thanks. Just provisioning now to dig into this for you. Thanks!

**Comment by noplanman** [comment]
@BronsonQuick Need anything else, just holla 😉 
Thanks!

**Comment by BronsonQuick** [comment]
@noplanman I'm not sure if you hit this issue: https://github.com/Chassis/Composer/issues/1 but that's fixed now. I'll keep digging into your issue now!

**Comment by BronsonQuick** [comment]
@noplanman I can confirm that I can replicate your issue now. I'll try and figure out a fix over the next day or two for you! Thanks very much for reporting it 😄

**Comment by noplanman** [comment]
@BronsonQuick How do I get the latest updates for the modules?
Is there a command I need to execute to update them?

**Comment by BronsonQuick** [comment]
Hey @noplanman,

There's a couple of ways you can update your extensions.
1) In your root Chassis directory run `git submodule update`. That should update your submodules. If it doesn't then try running `git submodule sync` or `git submodule update --init`
2) Do `cd extensions/phpmyadmin` and do `git checkout master && git pull`

If you have any trouble with those then let me know as I'm happy to help!

**Comment by noplanman** [comment]
Hola @BronsonQuick!

Thanks! So this should update everything, right?
`git submodule update; find extensions/ -maxdepth 1 -type d -exec git pull {} \;`

**Comment by BronsonQuick** [comment]
Hey @noplanman `git submodule update --recursive` will do all your submodules for you. I don't think I have any submodules inside our extensions from memory so the `--recursive` flag isn't really needed but I tend to always add it as it's a good habit!

**Comment by noplanman** [comment]
Ok, thanks guys!

@rmccue What about this one?
`$ git submodule update --recursive; for D in $(\ls extensions); do echo "Updating $D extension"; pushd "extensions/$D" >/dev/null; git checkout master; git pull; git submodule update --recursive; popd; done`

(I just love one-liners 😋)
